# Generated by Django 4.2.5 on 2023-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='company',
            field=models.CharField(default='ROSSI', max_length=20),
        ),
    ]
