# Generated by Django 4.2.5 on 2023-09-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
                ('hwtype', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('stag', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pdate', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=50)),
                ('rdate', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
        ),
    ]
