# Generated by Django 4.2.5 on 2023-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='ident',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pdate',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rdate',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
