# Generated by Django 4.2.5 on 2023-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_equipment_ident_alter_equipment_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='licence',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
