# Generated by Django 4.2.5 on 2023-09-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_equipment_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='pdate',
            field=models.DateTimeField(blank=True, max_length=50),
        ),
    ]
