# Generated by Django 4.2.5 on 2023-09-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_equipment_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='pdate',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
