# Generated by Django 4.2.5 on 2023-09-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_equipment_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='company',
            field=models.CharField(choices=[('rossi', 'Rossi Biofuel Zrt.'), ('enviral', 'Enviral a.s.')], default='rossi', max_length=50),
        ),
    ]
